apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopify-monitor.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "shopify-monitor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.json: |
{{ .Files.Get "config.json" | nindent 4 }}
